export const DEFAULT_TECHNICAL_SPEC_TYPE_OPTIONS = [
  "Dimensiones",
  "Peso",
  "Material",
  "Color",
  "Acabado",
  "Longitud",
  "Compatibilidad",
  "Uso recomendado",
  "Alimentacion",
  "Voltaje",
  "Potencia",
  "Conectividad",
  "Tipo de conexion",
  "Bluetooth",
  "USB",
  "Entrada auxiliar",
  "Entradas",
  "Salidas",
  "Conectores",
  "Canales",
  "Frecuencia",
  "Respuesta en frecuencia",
  "Sensibilidad",
  "Cobertura",
  "Capacidad",
  "Autonomia",
  "Tiempo de carga",
  "Resistencia / IP",
  "Instalacion",
  "Funciones",
  "Incluye accesorios",
  "Accesorios",
  "Garantia",
  "Numero de piezas",
  "Numero de teclas",
  "Numero de cuerdas",
  "Escala / menzura",
  "Patron polar",
  "Diametro",
  "Profundidad",
  "Tipo de parche",
  "Otro",
] as const;

export type TechnicalSpecTypeOption =
  (typeof DEFAULT_TECHNICAL_SPEC_TYPE_OPTIONS)[number];
